name: Build .NET Core Azure Function Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  AZURE_FUNCTIONAPP_NAME: msc101-func  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.301'

jobs:
  build:
    name: Build and deploy Azure Function app

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup .NET ${{ env.DOTNET_VERSION}} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build Project
      run: dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/azure-func-managed-identity-sample.csproj --configuration Release --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
